glance_helm_values:
  pod:
    replicas:
      api: 1
      
glance_images:
  - name: cirros
    url: http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
    min_disk: 1
    disk_format: raw
    container_format: bare
    is_public: true

  - name: Ubuntu 22.04 LTS
    url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    min_disk: 20
    disk_format: raw
    container_format: bare
    is_public: true